### ISSUE TITLE
API Docs not consistent

### ISSUE THREAD

**Issue by g4dpz** [infostellarinc/stellarstation-api#110]
The Readme.md for grade has:

_dependencies {
    compile 'com.stellarstation.api:stellarstation-api:**0.2.0**'
}_

whereas the java demo for gradle has:

_dependencies {
    compile 'com.google.auth:google-auth-library-oauth2-http:0.9.1'
    compile 'com.stellarstation.api:stellarstation-api:**0.0.8**'
    ['auth', 'netty', 'protobuf', 'stub'].each {
        compile "io.grpc:grpc-$it:1.16.1"
    }
    compile 'io.netty:netty-tcnative-boringssl-static:2.0.17.Final'
    compile 'org.slf4j:slf4j-simple:1.7.25'
}_

to use with the fake server from git I had to use this in maven to get the PrintingClient
 going:

  _<dependencies>
    <dependency>
      <groupId>com.stellarstation.api</groupId>
      <artifactId>stellarstation-api</artifactId>
      <version>**0.0.6**</version>
    </dependency>
    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
      <version>0.12.0</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.5</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.6.4</version>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-auth</artifactId>
      <version>1.17.1</version>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <version>1.17.1</version>
    </dependency>
    <dependency>
      **<groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.5.1</version>**
    </dependency>
  </dependencies>_

My java client:

[PrintingClientMain.java.txt](https://github.com/infostellarinc/stellarstation-api/files/2727188/PrintingClientMain.java.txt)

**Comment by anuraaga** [comment]
Thanks for reporting! Indeed the example code is using old versions of the API before we fixed to preserving compatibility which might be causing issues. We'll update the code, and make sure to update before releasing new versions.

To confirm what's happening, could you post any log of the problem you were having?

**Comment by g4dpz** [comment]
The usual maven dependencies :-)
gprc, protobuf & oauth2
I would have to revert back several days to start from the vanilla source :-(

**Comment by g4dpz** [comment]
Do yo have a version 2 fake server?

**Comment by g4dpz** [comment]
Could not resolve dependencies for project com.badgersoft:stellarstation-java-client:jar:1.0-SNAPSHOT: Failure to find com.stellarstation.api:stellarstation-api:jar:0.2.0 in https://repo.maven.apache.org/maven2

**Comment by g4dpz** [comment]
Do I need a specific repo definition?

**Comment by g4dpz** [comment]
My example code written in Java / Maven 

but getting proto buff errors should I change the version?

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/davidjohnson/.m2/repository/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1280 [grpc-default-executor-1] INFO com.badgersoft.infostellarclient.PrintingClientMain - Got response: /Fd9vGhlBiI5TIWQDOlf5RALYH8qAXfiRJzgEHYPy2p748Ld27EW44zTZMhAmU6gYRPg4u83T046V8LIY+5mGpcCCuoIZRuF4JPw
1281 [grpc-default-executor-1] INFO com.badgersoft.infostellarclient.PrintingClientMain - Got response: YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh
1281 [grpc-default-executor-1] INFO com.badgersoft.infostellarclient.PrintingClientMain - Got response: YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJi
1281 [grpc-default-executor-1] INFO com.badgersoft.infostellarclient.PrintingClientMain - Got response: Y2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2Nj`

[javaclient.zip](https://github.com/infostellarinc/stellarstation-api/files/2727356/javaclient.zip)

Dave

**Comment by g4dpz** [comment]
May be worth mentioning this when quoting the maven dependency for version 0.2.0

  ```
<repositories>
   ......
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
    ......
  </repositories>
```

**Comment by g4dpz** [comment]
Happy for you to use my example for the proposal in:

> Add integration tests in various languages #95
