### ISSUE TITLE
Update Python printing-client to use Queue instead of loop inlining command requests

### ISSUE THREAD

**Issue by anuraaga** [infostellarinc/stellarstation-api#122]
Currently, our Python example has a loop with a `sleep` that generates requests. This is not very representative of real use cases, so it would be better if we move the request generating to a separate thread and use `Queue` to pass them into the stream, which is probably the standard pattern for Python request streams.

**Comment by anuraaga** [comment]
Also just for reference, I happened to find this library that implements a simpler API for python streaming. I don't think we should switch to it for examples since it's not official but it could be good to look at.

**Comment by hoshir** [comment]
The printing-client for Python is updated to use Queue.
