### ISSUE TITLE
SSL API Access

### ISSUE THREAD

**Issue by g4dpz** [infostellarinc/stellarstation-api#125]
Hi,

I am having trouble accessing the API under OS X Java 1.8 using:

// Setup the gRPC client.
        ManagedChannel channel =
                ManagedChannelBuilder.forAddress("api.stellarstation.com", 443)
                        .build();

        StellarStationServiceGrpc.StellarStationServiceStub client =
                StellarStationServiceGrpc.newStub(channel)
                        .withCallCredentials(MoreCallCredentials.from(credentials));

I get: 

14:52:57,410 ERROR [stderr] (grpc-default-executor-1) Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
14:52:57,410 ERROR [stderr] (grpc-default-executor-1) 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
14:52:57,410 ERROR [stderr] (grpc-default-executor-1) 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
14:52:57,410 ERROR [stderr] (grpc-default-executor-1) 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
14:52:57,410 ERROR [stderr] (grpc-default-executor-1) 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

Looking at my Java cacerts file, I see the following 'Owners'

Owner: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Owner: CN=COMODO RSA Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
Owner: EMAILADDRESS=premium-server@thawte.com, CN=Thawte Premium Server CA, OU=Certification Services Division, O=Thawte Consulting cc, L=Cape Town, ST=Western Cape, C=ZA
Owner: CN=SwissSign Platinum CA - G2, O=SwissSign AG, C=CH
Owner: CN=SwissSign Silver CA - G2, O=SwissSign AG, C=CH
Owner: CN=Equifax Secure eBusiness CA-1, O=Equifax Secure Inc., C=US
Owner: CN=SecureTrust CA, O=SecureTrust Corporation, C=US
Owner: CN=UTN-USERFirst-Client Authentication and Email, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
Owner: CN=AffirmTrust Networking, O=AffirmTrust, C=US
Owner: CN=Entrust Root Certification Authority, OU="(c) 2006 Entrust, Inc.", OU=www.entrust.net/CPS is incorporated by reference, O="Entrust, Inc.", C=US
Owner: CN=UTN-USERFirst-Hardware, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R5
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R4
Owner: CN=Certum CA, O=Unizeto Sp. z o.o., C=PL
Owner: CN=AddTrust Class 1 CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE
Owner: CN=Entrust Root Certification Authority - G2, OU="(c) 2009 Entrust, Inc. - for authorized use only", OU=See www.entrust.net/legal-terms, O="Entrust, Inc.", C=US
Owner: OU=Equifax Secure Certificate Authority, O=Equifax, C=US
Owner: CN=QuoVadis Root CA 3, O=QuoVadis Limited, C=BM
Owner: CN=QuoVadis Root CA 2, O=QuoVadis Limited, C=BM
Owner: CN=Swisscom Root CA 2, OU=Digital Certificate Services, O=Swisscom, C=ch
Owner: CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Owner: CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
Owner: CN=GeoTrust Universal CA, O=GeoTrust Inc., C=US
Owner: OU=Class 3 Public Primary Certification Authority, O="VeriSign, Inc.", C=US
Owner: CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
Owner: CN=thawte Primary Root CA - G2, OU="(c) 2007 thawte, Inc. - For authorized use only", O="thawte, Inc.", C=US
Owner: CN=Deutsche Telekom Root CA 2, OU=T-TeleSec Trust Center, O=Deutsche Telekom AG, C=DE
Owner: CN=Buypass Class 3 Root CA, O=Buypass AS-983163327, C=NO
Owner: CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
Owner: CN=GeoTrust Primary Certification Authority, O=GeoTrust Inc., C=US
Owner: CN=Buypass Class 2 Root CA, O=Buypass AS-983163327, C=NO
Owner: CN=Baltimore CyberTrust Code Signing Root, OU=CyberTrust, O=Baltimore, C=IE
Owner: OU=Class 1 Public Primary Certification Authority, O="VeriSign, Inc.", C=US
Owner: CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE
Owner: OU=Starfield Class 2 Certification Authority, O="Starfield Technologies, Inc.", C=US
Owner: CN=Actalis Authentication Root CA, O=Actalis S.p.A./03358520967, L=Milan, C=IT
Owner: CN=Chambers of Commerce Root, OU=http://www.chambersign.org, O=AC Camerfirma SA CIF A82743287, C=EU
Owner: CN=T-TeleSec GlobalRoot Class 3, OU=T-Systems Trust Center, O=T-Systems Enterprise Services GmbH, C=DE
Owner: CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: CN=T-TeleSec GlobalRoot Class 2, OU=T-Systems Trust Center, O=T-Systems Enterprise Services GmbH, C=DE
Owner: CN=VeriSign Class 3 Public Primary Certification Authority - G4, OU="(c) 2007 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: CN=VeriSign Class 3 Public Primary Certification Authority - G3, OU="(c) 1999 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: CN=XRamp Global Certification Authority, O=XRamp Security Services Inc, OU=www.xrampsecurity.com, C=US
Owner: CN=Entrust Root Certification Authority - EC1, OU="(c) 2012 Entrust, Inc. - for authorized use only", OU=See www.entrust.net/legal-terms, O="Entrust, Inc.", C=US
Owner: CN=Class 3P Primary CA, O=Certplus, C=FR
Owner: CN=Certum Trusted Network CA, OU=Certum Certification Authority, O=Unizeto Technologies S.A., C=PL
Owner: OU=VeriSign Trust Network, OU="(c) 1998 VeriSign, Inc. - For authorized use only", OU=Class 3 Public Primary Certification Authority - G2, O="VeriSign, Inc.", C=US
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3
Owner: CN=UTN - DATACorp SGC, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, ST=UT, C=US
Owner: OU=Security Communication RootCA2, O="SECOM Trust Systems CO.,LTD.", C=JP
Owner: CN=GTE CyberTrust Global Root, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US
Owner: OU=Security Communication RootCA1, O=SECOM Trust.net, C=JP
Owner: CN=AffirmTrust Commercial, O=AffirmTrust, C=US
Owner: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R2
Owner: CN=Class 2 Primary CA, O=Certplus, C=FR
Owner: CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Owner: CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE
Owner: CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
Owner: CN=Starfield Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US
Owner: CN=GeoTrust Global CA, O=GeoTrust Inc., C=US
Owner: CN=Sonera Class2 CA, O=Sonera, C=FI
Owner: CN=Swisscom Root EV CA 2, OU=Digital Certificate Services, O=Swisscom, C=ch
Owner: CN=Thawte Timestamping CA, OU=Thawte Certification, O=Thawte, L=Durbanville, ST=Western Cape, C=ZA
Owner: CN=Sonera Class1 CA, O=Sonera, C=FI
Owner: CN=QuoVadis Root Certification Authority, OU=Root Certification Authority, O=QuoVadis Limited, C=BM
Owner: CN=AffirmTrust Premium ECC, O=AffirmTrust, C=US
Owner: CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US
Owner: CN=AAA Certificate Services, O=Comodo CA Limited, L=Salford, ST=Greater Manchester, C=GB
Owner: CN=America Online Root Certification Authority 2, O=America Online Inc., C=US
Owner: CN=AddTrust Qualified CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE
Owner: CN=KEYNECTIS ROOT CA, OU=ROOT, O=KEYNECTIS, C=FR
Owner: CN=America Online Root Certification Authority 1, O=America Online Inc., C=US
Owner: CN=VeriSign Class 2 Public Primary Certification Authority - G3, OU="(c) 1999 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: CN=AddTrust External CA Root, OU=AddTrust External TTP Network, O=AddTrust AB, C=SE
Owner: CN=LuxTrust Global Root, O=LuxTrust s.a., C=LU
Owner: OU=VeriSign Trust Network, OU="(c) 1998 VeriSign, Inc. - For authorized use only", OU=Class 2 Public Primary Certification Authority - G2, O="VeriSign, Inc.", C=US
Owner: CN=GeoTrust Primary Certification Authority - G3, OU=(c) 2008 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US
Owner: CN=GeoTrust Primary Certification Authority - G2, OU=(c) 2007 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US
Owner: CN=SwissSign Gold CA - G2, O=SwissSign AG, C=CH
Owner: CN=Entrust.net Certification Authority (2048), OU=(c) 1999 Entrust.net Limited, OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), O=Entrust.net
Owner: OU=ePKI Root Certification Authority, O="Chunghwa Telecom Co., Ltd.", C=TW
Owner: CN=Global Chambersign Root - 2008, O=AC Camerfirma S.A., SERIALNUMBER=A82743287, L=Madrid (see current address at www.camerfirma.com/address), C=EU
Owner: CN=Chambers of Commerce Root - 2008, O=AC Camerfirma S.A., SERIALNUMBER=A82743287, L=Madrid (see current address at www.camerfirma.com/address), C=EU
Owner: CN=USERTrust ECC Certification Authority, O=The USERTRUST Network, L=Jersey City, ST=New Jersey, C=US
Owner: OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group, Inc.", C=US
Owner: CN=AffirmTrust Premium, O=AffirmTrust, C=US
Owner: CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jersey City, ST=New Jersey, C=US
Owner: CN=VeriSign Class 1 Public Primary Certification Authority - G3, OU="(c) 1999 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
Owner: OU=Security Communication EV RootCA1, O="SECOM Trust Systems CO.,LTD.", C=JP
Owner: OU=VeriSign Trust Network, OU="(c) 1998 VeriSign, Inc. - For authorized use only", OU=Class 1 Public Primary Certification Authority - G2, O="VeriSign, Inc.", C=US
Owner: CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
Owner: CN=Go Daddy Root Certificate Authority - G2, O="GoDaddy.com, Inc.", L=Scottsdale, ST=Arizona, C=US

Do I need to add you certificates?

Regards

Dave Johnson (G4DPZ Amateur Groundstation)

**Comment by g4dpz** [comment]
Hi,

Had to create a jssecacerts file using: 

http://blogs.sun.com/andreas/resource/InstallCert.java

Getting further now.

Regards

Dave

**Comment by anuraaga** [comment]
Thanks for the update! The link isn't working for me, is there any other link to that info? I haven't heard of Oracle JDK ever lacking certs, though OpenJDK was lacking them until Java 10. Are you by chance using openjdk 8? If you're using Oracle JDK 8 I can't think of any reason for this other than a corrupt installation but hope that's not the case.

**Comment by g4dpz** [comment]
Hi

Using OS X Java 8

Will try it on under Ubuntu 

And find the correct link.

Dave
