### ISSUE TITLE
Client method ListUnavailabilityWindowsResponse not resolved

### ISSUE THREAD

**Issue by g4dpz** [infostellarinc/stellarstation-api#126]
Using API 0.2.0

Intellij Idea Java cannot resolve ListUnavailabilityWindowsResponse

<img width="1311" alt="Screenshot 2019-04-07 at 11 02 29" src="https://user-images.githubusercontent.com/553352/55682002-f2e06e00-5924-11e9-9416-fa169a4a6a37.png">

<img width="552" alt="Screenshot 2019-04-07 at 11 06 53" src="https://user-images.githubusercontent.com/553352/55682030-54084180-5925-11e9-964e-3d283fdc44f7.png">

**Comment by g4dpz** [comment]
why are all end points not implemented:

<img width="1158" alt="Screenshot 2019-04-07 at 11 15 37" src="https://user-images.githubusercontent.com/553352/55682112-97af7b00-5926-11e9-9135-e2ae11f986d0.png">

**Comment by anuraaga** [comment]
`StellarStationService` only contains APIs for satellite operators.

A different class / package, `GroundStationService` has the ground station ones. Every service has a corresponding class in the jar.

https://github.com/infostellarinc/stellarstation-api/blob/master/api/src/main/proto/stellarstation/api/v1/groundstation/groundstation.proto

**Comment by g4dpz** [comment]
Hi,

Thanks, maybe we need to add and example of that to.

- Dave

**Comment by g4dpz** [comment]
Hi,

Worked, THANK YOU

- Dave

**Comment by anuraaga** [comment]
Thanks for the feedback - lately we've been writing integration tests as pat of #95  to be examples for Python, but it would be nice to have for Java too, but maybe the python examples can also provide some extra insights

https://github.com/infostellarinc/stellarstation-api/tree/master/integration-tests/python

**Comment by g4dpz** [comment]
Happy to provide some more Java examples if it helps.

- Dave

**Comment by g4dpz** [comment]
Worked :-)



Thanks,

Dave
