### ISSUE TITLE
./gradle :stubs:golang:copyDepsToMockgenGopath fails

### ISSUE THREAD

**Issue by kenichi-fukushima** [infostellarinc/stellarstation-api#133]
https://github.com/infostellarinc/stellarstation-api/pull/132 broke the build. The gradle task does not handle the copy right comment added to `stubs/golang/go.mod`. I'm not sure go.mod needs a copy right notice.

**Comment by danada** [comment]
Running `./gradlew :stubs:golang:copyDepsToMockgenGopath --rerun-tasks` completed successfully-- not able to repro this so will close.
