### ISSUE TITLE
Typo in CLA text

### ISSUE THREAD

**Issue by chokoswitch** [infostellarinc/stellarstation-api#163]
CLA text starts with this sentence that has a couple of spelling mistakes in it

```
Note: Pleaes fill the form at https://goo.gl/forms/4ired0eRKcK42JGJ3 if you are going to contribute on behalf of your compnay.
```

**Comment by hoshir** [comment]
Thanks for reporting the issue. We have fixed the CLA which will ask you to sign it again.
