### ISSUE TITLE
Fakeserver not setting timeLastByteReceived 

### ISSUE THREAD

**Issue by laurikimmel** [infostellarinc/stellarstation-api#33]
Looks to be simple copy-paste error.

```setTimeFirstByteReceived``` is called twice instead of of setting ```timeFirstByteReceived``` and ```timeLastByteReceived```.

https://github.com/infostellarinc/stellarstation-api/blob/1fefd5a3b2d3f88259d2aaf67301e3693f263f55/examples/fakeserver/src/main/java/com/stellarstation/api/fakeserver/FakeStellarStationService.java#L117

**Comment by anuraaga** [comment]
Thanks for reporting!
