### ISSUE TITLE
Configuration options for Fakeserver

### ISSUE THREAD

**Issue by laurikimmel** [infostellarinc/stellarstation-api#34]
Consider adding configuration variables to Fakeserver to make it more flexible.

For example
* telemetry publishing frequency. Eg. for testing slower / faster data reception
* telemetry payload size. Eg. for testing bigger / smaller telemetry payloads
* session timeout. Eg. testing session end without need to wait 5 minutes
* etc

Please make sure config options can be set using Docker container environment variables when running Fakeserver from Docker image. Eg.

```
$ docker run -e TM_PUBLISHING_FREQUENCY=100ms -e TM_PAYLOAD_SIZE=100KB -p 8080:8080 -p 8081:8081 -it --rm quay.io/infostellarinc/fake-apiserver
```

**Comment by anuraaga** [comment]
Thanks will add these knobs. By the way, what do you think about setting via an environment variable that sets system properties? `JAVA_OPTS="-Dtelemetry.publishingFrequency=100ms"`, etc? We can actually support both just wondering if you have a preference for either.
