### ISSUE TITLE
Receiving Groundstation ID or Name from a Plan

### ISSUE THREAD

**Issue by eral22** [infostellarinc/stellarstation-api#78]
The StellarAPI seems not to include a ground station id or name after reserving a pass in the API definition (v0.1.0). Is that intended behaviour or is there an upgrade planned in a future version? How can I get the ground station id / name for a Plan? 

### Steps to reproduce
• Reserve a pass with the `ReservePass` function

• Returned Answer for the `Plan` in the `ReservePassRespone`:

```
plan {  
    id: "1513725273"  
    satellite_id: "107"  
    aos_time {    seconds: 1541146021  }  
    los_time {    seconds: 1541146621  }  
    ground_station_latitude: 35.7  
    ground_station_longitude: 139.7  
    ground_station_country_code: "JP"  
    max_elevation_degrees: 66.47344807360012  
    max_elevation_time {    seconds: 1541146321  }  
    downlink_center_frequency_hz: 401000000  
    uplink_center_frequency_hz: 430000000
}
```
• No groundstation id or name included in the response. Only location coordinates and a country code.

### Environment
Java using stellarstation-api 0.1.0

**Comment by anuraaga** [comment]
Thanks for reporting! We currently don't have any APIs that accept ground station ID as an input and have not thought of a use case that would require it. We prefer to return relevant information about the ground station (such as location, frequency, and in the future radio information) instead so satellite operators can use the info in planning. A name doesn't provide extra information AFAIU and we are encouraging a model that does not consider individual ground stations as much as possible, just passes and communication time.

What is your use case for an actual ground station ID?

**Comment by eral22** [comment]
I thought more of the **output** of the API after reserving a pass (ReservePass) or listing the passess (ListUpcomingAvailablePasses). So does this mean the satellite operator shoud derive the GS name / id in concern from the location and country code?
As a satellite operator I want to exactly know at which groundstation (prefereably identified with a unique id / name) my data will be dumped. So I can use that information e.g. in a GUI to show the operator on which groundstation (with a name) the next upcoming pass is.

**Comment by anuraaga** [comment]
Actually, we don't think there is a need for a ground station name or ID of any sort presented to our users and recommend you don't try to create one. When using StellarStation, satellite operators connect to a standard API, and don't connect to individual ground stations. Therefore there is never any need to know the name of a ground station. We do understand that it is important to know general information about a ground station like lat/lng and radio information for decisions and if you think there is any descriptive information missing we would be happy to consider adding it - please feel free to open a ticket anytime when you need such descriptive information. But we do hope to provide a service where users can forget about the concept of ground station completely and just get their data :) So in general we will continue to favor leaving ground station IDs out of the satellite-side APIs.

**Comment by laurikimmel** [comment]
@anuraaga - although I can understand your reasoning in some extent, would you reconsider the original request now that GS location is clearly visible in StellarStation web console?

![GS-location](https://user-images.githubusercontent.com/476134/60402629-ce4e0800-9b9a-11e9-84fd-bb41300c56cb.png)

Not having a simple human readable GS name / label / ID returned by API makes us to assign one our self to make things simpler for endusers. 

Imagine discussion between two operators - _"when is next pass in Japan at longitude 139.549806 and latitude 35.405556?"_ vs _"when is next pass at Yokohama C?"_.

**Comment by anuraaga** [comment]
@laurikimmel I'm not at Infostellar anymore. But given the screenshot, I suspect @hoshir and the team are working on returning that string in the API.

**Comment by hoshir** [comment]
Hi @laurikimmel, there is a small update about GS name; now we return [ground station organization name](https://github.com/infostellarinc/stellarstation-api/blob/master/api/src/main/proto/stellarstation/api/v1/stellarstation.proto#L406) in passes and plans message for satellite operators, and [satellite organization name](https://github.com/infostellarinc/stellarstation-api/blob/master/api/src/main/proto/stellarstation/api/v1/groundstation/groundstation.proto#L206) for ground station owners.
